# Generated by Django 2.0.9 on 2025-05-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=8, null=True)),
                ('bmi', models.FloatField(null=True)),
                ('bmi_category', models.CharField(max_length=100, null=True)),
                ('pal', models.CharField(blank=True, choices=[('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9'), ('2.0', '2.0'), ('2.2', '2.2')], default='1.2', max_length=3, null=True)),
                ('bmr', models.FloatField(null=True)),
                ('tmr', models.FloatField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Register')),
            ],
        ),
    ]
