# Generated by Django 2.0.9 on 2025-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_calculateddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietitians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Qualification', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('profile', models.ImageField(null=True, upload_to='profile/')),
            ],
        ),
    ]
