# Generated by Django 2.0.9 on 2025-05-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_dietitianlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membershipplans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, null=True)),
                ('price_per_month', models.FloatField(null=True)),
                ('duration_in_months', models.FloatField(null=True)),
                ('personal_trainer', models.BooleanField(default=False)),
                ('Amount_of_people', models.FloatField(null=True)),
                ('number_of_visits', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
