# Generated by Django 2.0.9 on 2025-05-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_membershipplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookappointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('height', models.CharField(max_length=4, null=True)),
                ('weight', models.CharField(max_length=3, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('bmi', models.FloatField(null=True)),
                ('bmi_category', models.CharField(max_length=100, null=True)),
                ('bmr', models.FloatField(null=True)),
                ('pal', models.CharField(max_length=3, null=True)),
                ('tmr', models.FloatField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Dietitians')),
            ],
        ),
    ]
