# Generated by Django 2.0.9 on 2025-05-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_beforeconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beforeplanconfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Membershipplans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Register')),
            ],
        ),
    ]
